name: bench

on:
  #schedule:
  #  - cron: 0 0 * * *
  push:

jobs:
  hello_bench:
    name: 'bench'
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Bun
        uses: antongolub/action-setup-bun@v1.4.0
        # with:
        #   bun-version: 0.1.10
      - name: Install workerd
        run: sudo npm install workerd
      - run: chmod 777 ./node_modules/@cloudflare/workerd-linux-64/bin/workerd
      - run: echo "$(pwd)/node_modules/@cloudflare/workerd-linux-64/bin/" >> $GITHUB_PATH
      # - run: workerd serve --verbose ./workerd/try.capnp
      #- name: Install Oha
      #  uses: actions-rs/install@v0.1
      #  with:
      #    crate: oha
      #    version: 0.5.4
      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Install wrk
        run: brew install wrk
      - name: change permission
        run: chmod 777 ./oha-linux-amd64
      - name: Run Benchmark
        run: deno task serve
